INSERT INTO public.droit_user(
	id_droit_user, code_droit_user, descri_droit_user, lib_droit_user)
VALUES (1, 'fichier',U&'Accerder au menu Fichier', ''),
 (2, 'fichier_exo',U&'Accerder au menu Exercice', ''),
 (3, 'fichier_exo_new',U&'Créer Exercice', ''),
 (4, 'fichier_exo_edit',U&'Modifier Exercice', ''),
 (5, 'fichier_exo_delete',U&'Supprimer Exercice', ''),
 (6, 'fichier_exo_close',U&'Cloturer Exercice', ''),
 (7, 'fichier_exo_select',U&'Selectionner Exercice', ''),

 (9, 'import',U&'Accerder au menu Importation', ''),
 (10, 'importation',U&'Faire des importations', ''),
 (11, 'exportation',U&'Faire des exportations', ''),

 (13, 'def',U&'Accerder au menu Définition', ''),
 (14, 'def_cat_centr',U&'Accerder au menu catégorie de centre', ''),
 (15, 'def_cat_centr_new',U&'Créer catégorie de centre', ''),
 (16, 'def_cat_centr_edit',U&'Modifier catégorie de centre', ''),
 (17, 'def_cat_centr_delete',U&'Supprimer catégorie de centre', ''),

 (19, 'def_centr_cons',U&'Accerder au menu centre de consommation', ''),
 (20, 'def_centr_cons_new',U&'Créer centre de consommation', ''),
 (21, 'def_centr_cons_edit',U&'Modifier centre de consommation', ''),
 (22, 'def_centr_cons_delete',U&'Supprimer centre de consommation', ''),

 (24, 'def_mag',U&'Accerder au menu Magasin', ''),
 (25, 'def_mag_new',U&'Créer Magasin', ''),
 (26, 'def_mag_edit',U&'Modifier Magasin', ''),
 (27, 'def_mag_delete',U&'Supprimer Magasin', ''),

 (29, 'def_fami_art',U&'Accerder au menu Famille d\0027Article', ''),
 (30, 'def_fami_art_new',U&'Créer Famille d\0027Article', ''),
 (31, 'def_fami_art_edit',U&'Modifier Famille d\0027Article', ''),
 (32, 'def_fami_art_delete',U&'Supprimer Famille d\0027Article', ''),

 (34, 'def_categ_art',U&'Accerder au menu Cartégorie d\0027Article', ''),
 (35, 'def_categ_art_new',U&'Créer Cartégorie d\0027Article', ''),
 (36, 'def_categ_art_edit',U&'Modifier Cartégorie d\0027Article', ''),
 (37, 'def_categ_art_delete',U&'Supprimer Cartégorie d\0027Article', ''),

 (39, 'def_unit_compt',U&'Accerder au menu Unité de Comptage', ''),
 (40, 'def_unit_compt_new',U&'Créer Unité de Comptage', ''),
 (41, 'def_unit_compt_edit',U&'Modifier Unité de Comptage', ''),
 (42, 'def_unit_compt_delete',U&'Supprimer Unité de Comptage', ''),

 (44, 'def_articl',U&'Accerder au menu Article', ''),
 (45, 'def_articl_new',U&'Créer Article', ''),
 (46, 'def_articl_edit',U&'Modifier Article', ''),
 (47, 'def_articl_delete',U&'Supprimer Article', ''),

 (49, 'def_cause_ano',U&'Accerder au menu Cause et Anomalie', ''),
 (50, 'def_cause_ano_new',U&'Créer Cause et Anomalie', ''),
 (51, 'def_cause_ano_edit',U&'Modifier Cause et Anomalie', ''),
 (52, 'def_cause_ano_delete',U&'Supprimer Cause et Anomalie', ''),

 (54, 'def_fournis',U&'Accerder au menu Fournisseur', ''),
 (55, 'def_fournis_new',U&'Créer Fournisseur', ''),
 (56, 'def_fournis_edit',U&'Modifier Fournisseur', ''),
 (57, 'def_fournis_delete',U&'Supprimer Fournisseur', ''),

 (59, 'saisie',U&'Accerder au menu Saisie', ''),
 (60, 'saisie_fact_prof',U&'Accerder au menu Factures Proformat (FP)', ''),
 (61, 'saisie_fact_prof_new',U&'Créer Factures Proformat (FP)', ''),
 (62, 'saisie_fact_prof_edit',U&'Modifier Factures Proformat (FP)', ''),
 (63, 'saisie_fact_prof_delete',U&'Supprimer Factures Proformat (FP)', ''),
 (64, 'saisie_fact_prof_valid',U&'Valider Factures Proformat (FP)', ''),
 (65, 'saisie_fact_prof_rollback',U&'Annuler Factures Proformat (FP)', ''),
 (66, 'saisie_fact_prof_detail',U&'Voir les détails sur Factures Proformat (FP)', ''),
 (67, 'saisie_fact_prof_print',U&'Imprimer Factures Proformat (FP)', ''),

 (69, 'saisie_dem_cota',U&'Accerder au menu Demande de Cotation (DC)', ''),
 (70, 'saisie_dem_cota_new',U&'Créer Demande de Cotation (DC)', ''),
 (71, 'saisie_dem_cota_edit',U&'Modifier Demande de Cotation (DC)', ''),
 (72, 'saisie_dem_cota_delete',U&'Supprimer Demande de Cotation (DC)', ''),
 (73, 'saisie_dem_cota_valid',U&'Valider Demande de Cotation (DC)', ''),
 (74, 'saisie_dem_cota_rollback',U&'Annuler Demande de Cotation (DC)', ''),
 (75, 'saisie_dem_cota_detail',U&'Voir les détails sur Demande de Cotation (DC)', ''),
 (76, 'saisie_dem_cota_print',U&'Imprimer Demande de Cotation (DC)', ''),

 (78, 'saisie_drp',U&'Accerder au menu Demande de Renseignement de Prix (DRP)', ''),
 (79, 'saisie_drp_new',U&'Créer Demande de Renseignement de Prix (DRP)', ''),
 (80, 'saisie_drp_edit',U&'Modifier Demande de Renseignement de Prix (DRP)', ''),
 (81, 'saisie_drp_delete',U&'Supprimer Demande de Renseignement de Prix (DRP)', ''),
 (82, 'saisie_drp_valid',U&'Valider Demande de Renseignement de Prix (DRP)', ''),
 (83, 'saisie_drp_rollback',U&'Annuler Demande de Renseignement de Prix (DRP)', ''),
 (84, 'saisie_drp_detail',U&'Voir les détails sur Demande de Renseignement de Prix (DRP)', ''),
 (85, 'saisie_drp_print',U&'Imprimer Demande de Renseignement de Prix (DRP)', ''),

 (87, 'saisie_aoo',U&'Accerder au menu Appel d\0027Offre Ouvert (AOO)', ''),
 (88, 'saisie_aoo_new',U&'Créer Appel d\0027Offre Ouvert (AOO)', ''),
 (89, 'saisie_aoo_edit',U&'Modifier Appel d\0027Offre Ouvert (AOO)', ''),
 (90, 'saisie_aoo_delete',U&'Supprimer Appel d\0027Offre Ouvert (AOO)', ''),
 (91, 'saisie_aoo_valid',U&'Valider Appel d\0027Offre Ouvert (AOO)', ''),
 (92, 'saisie_aoo_rollback',U&'Annuler Appel d\0027Offre Ouvert (AOO)', ''),
 (93, 'saisie_aoo_detail',U&'Voir les détails sur Appel d\0027Offre Ouvert (AOO)', ''),
 (94, 'saisie_aoo_print',U&'Imprimer Appel d\0027Offre Ouvert (AOO)', ''),

 (96, 'saisie_ed',U&'Accerder au menu Entente Directe (ED)', ''),
 (97, 'saisie_ed_new',U&'Créer Entente Directe (ED)', ''),
 (98, 'saisie_ed_edit',U&'Modifier Entente Directe (ED)', ''),
 (99, 'saisie_ed_delete',U&'Supprimer Entente Directe (ED)', ''),
 (100, 'saisie_ed_valid',U&'Valider Entente Directe (ED)', ''),
 (101, 'saisie_ed_rollback',U&'Annuler Entente Directe (ED)', ''),
 (102, 'saisie_ed_detail',U&'Voir les détails sur Entente Directe (ED)', ''),
 (103, 'saisie_ed_print',U&'Imprimer Entente Directe (ED)', ''),

 (105, 'saisie_pi',U&'Accerder au menu Prestation Intellectuelle (PI)', ''),
 (106, 'saisie_pi_new',U&'Créer Prestation Intellectuelle (PI)', ''),
 (107, 'saisie_pi_edit',U&'Modifier Prestation Intellectuelle (PI)', ''),
 (108, 'saisie_pi_delete',U&'Supprimer Prestation Intellectuelle (PI)', ''),
 (109, 'saisie_pi_valid',U&'Valider Prestation Intellectuelle (PI)', ''),
 (110, 'saisie_pi_rollback',U&'Annuler Prestation Intellectuelle (PI)', ''),
 (111, 'saisie_pi_detail',U&'Voir les détails sur Prestation Intellectuelle (PI)', ''),
 (112, 'saisie_pi_print',U&'Imprimer Prestation Intellectuelle (PI)', ''),

 (114, 'saisie_ami',U&'Accerder au menu Appel à Manisfectation d\0027Intérêt (AMI)', ''),
 (115, 'saisie_ami_new',U&'Créer Appel à Manisfectation d\0027Intérêt (AMI)', ''),
 (116, 'saisie_ami_edit',U&'Modifier Appel à Manisfectation d\0027Intérêt (AMI)', ''),
 (117, 'saisie_ami_delete',U&'Supprimer Appel à Manisfectation d\0027Intérêt (AMI)', ''),
 (118, 'saisie_ami_valid',U&'Valider Appel à Manisfectation d\0027Intérêt (AMI)', ''),
 (119, 'saisie_ami_rollback',U&'Annuler Appel à Manisfectation d\0027Intérêt (AMI)', ''),
 (120, 'saisie_ami_detail',U&'Voir les détails sur Appel à Manisfectation d\0027Intérêt (AMI)', ''),
 (121, 'saisie_ami_print',U&'Imprimer Appel à Manisfectation d\0027Intérêt (AMI)', ''),

 (123, 'saisie_ca',U&'Accerder au menu Commande Achat (CA)', ''),
 (124, 'saisie_ca_new',U&'Créer Commande Achat (CA)', ''),
 (125, 'saisie_ca_edit',U&'Modifier Commande Achat (CA)', ''),
 (126, 'saisie_ca_delete',U&'Supprimer Commande Achat (CA)', ''),
 (127, 'saisie_ca_valid',U&'Valider Commande Achat (CA)', ''),
 (128, 'saisie_ca_rollback',U&'Annuler Commande Achat (CA)', ''),
 (129, 'saisie_ca_detail',U&'Voir les détails sur Commande Achat (CA)', ''),
 (130, 'saisie_ca_print',U&'Imprimer Commande Achat (CA)', ''),

 (132, 'saisie_lc',U&'Accerder au menu Lettre de Commande (LC)', ''),
 (133, 'saisie_lc_new',U&'Créer Lettre de Commande (LC)', ''),
 (134, 'saisie_lc_edit',U&'Modifier Lettre de Commande (LC)', ''),
 (135, 'saisie_lc_delete',U&'Supprimer Lettre de Commande (LC)', ''),
 (136, 'saisie_lc_valid',U&'Valider Lettre de Commande (LC)', ''),
 (137, 'saisie_lc_rollback',U&'Annuler Lettre de Commande (LC)', ''),
 (138, 'saisie_lc_detail',U&'Voir les détails sur Lettre de Commande (LC)', ''),
 (139, 'saisie_lc_print',U&'Imprimer Lettre de Commande (LC)', ''),

 (141, 'saisie_cmd',U&'Accerder au menu Caisse Menu Dépense (CMD)', ''),
 (142, 'saisie_cmd_new',U&'Créer Caisse Menu Dépense (CMD)', ''),
 (143, 'saisie_cmd_edit',U&'Modifier Caisse Menu Dépense (CMD)', ''),
 (144, 'saisie_cmd_delete',U&'Supprimer Caisse Menu Dépense (CMD)', ''),
 (145, 'saisie_cmd_valid',U&'Valider Caisse Menu Dépense (CMD)', ''),
 (146, 'saisie_cmd_rollback',U&'Annuler Caisse Menu Dépense (CMD)', ''),
 (147, 'saisie_cmd_detail',U&'Voir les détails sur Caisse Menu Dépense (CMD)', ''),
 (148, 'saisie_cmd_print',U&'Imprimer Caisse Menu Dépense (CMD)', ''),

 (150, 'saisie_stck_init',U&'Accerder au menu Stock Initial', ''),
 (151, 'saisie_stck_init_new',U&'Créer Stock Initial', ''),

 (153, 'saisie_recept',U&'Accerder au menu Entrée d\0027Article', ''),
 (154, 'saisie_recept_new',U&'Créer Entrée d\0027Article', ''),
 (155, 'saisie_recept_edit',U&'Modifier Entrée d\0027Article', ''),
 (156, 'saisie_recept_delete',U&'Supprimer Entrée d\0027Article', ''),
 (157, 'saisie_recept_valid',U&'Valider Entrée d\0027Article', ''),
 (158, 'saisie_recept_rollback',U&'Annuler Entrée d\0027Article', ''),
 (159, 'saisie_recept_detail',U&'Voir les détails sur Entrée d\0027Article', ''),
 (160, 'saisie_recept_print',U&'Imprimer Entrée d\0027Article', ''),

 (162, 'saisie_etat_stock',U&'Accerder au menu Etat de Stock', ''),

 (164, 'saisie_dem_bes',U&'Accerder au menu Demande de Besoins', ''),
 (165, 'saisie_dem_bes_new',U&'Créer Demande de Besoins', ''),
 (166, 'saisie_dem_bes_edit',U&'Modifier Demande de Besoins', ''),
 (167, 'saisie_dem_bes_delete',U&'Supprimer Demande de Besoins', ''),
 (168, 'saisie_dem_bes_valid',U&'Valider Demande de Besoins', ''),
 (169, 'saisie_dem_bes_rollback',U&'Annuler Demande de Besoins', ''),
 (170, 'saisie_dem_bes_detail',U&'Voir les détails sur Demande de Besoins', ''),
 (171, 'saisie_dem_bes_print',U&'Imprimer Demande de Besoins', ''),

 (173, 'saisie_servir',U&'Accerder au menu Servir', ''),
 (174, 'saisie_servir_new',U&'Créer Servir', ''),
 (175, 'saisie_servir_edit',U&'Modifier Servir', ''),
 (176, 'saisie_servir_delete',U&'Supprimer Servir', ''),
 (177, 'saisie_servir_valid',U&'Valider Servir', ''),
 (178, 'saisie_servir_rollback',U&'Annuler Servir', ''),
 (179, 'saisie_servir_detail',U&'Voir les détails sur Servir', ''),
 (180, 'saisie_servir_print',U&'Imprimer Servir', ''),

 (182, 'saisie_inv',U&'Accerder au menu Inventaire', ''),
 (183, 'saisie_inv_new',U&'Créer Inventaire', ''),
 (184, 'saisie_inv_edit',U&'Modifier Inventaire', ''),
 (185, 'saisie_inv_delete',U&'Supprimer Inventaire', ''),
 (186, 'saisie_inv_valid',U&'Valider Inventaire', ''),
 (187, 'saisie_inv_rollback',U&'Annuler Inventaire', ''),
 (188, 'saisie_inv_detail',U&'Voir les détails sur Inventaire', ''),
 (189, 'saisie_inv_print',U&'Imprimer Inventaire', ''),

 (191, 'saisie_clot_peri',U&'Accerder au menu Clotûre de Période', ''),
 (192, 'saisie_clot_peri_new',U&'Créer Clotûre de Période', ''),

 (194, 'compta',U&'Accerder au menu Comptabilisation', ''),
 (195, 'compta_cg',U&'Accerder au menu Compte Généraux dans Comptabilisation', ''),

 (197, 'compta_oja',U&'Accerder au menu Opération et Journal Associé dans Comptabilisation', ''),

 (199, 'compta_iacdj',U&'Accerder au menu Imputation des Articles et Config. Des Journaux dans Comptabilisation', ''),

 (201, 'compta_gec',U&'Accerder au menu Génération des écritures comptables dans Comptabilisation', ''),

 (203, 'rapport',U&'Accerder au menu Rapports', ''),
 (204, 'rapport_apf',U&'Accerder au menu Article Par Famille dans Rapports', ''),

 (206, 'rapport_ce',U&'Accerder au menu Commandes ou Engagements dans Rapports', ''),

 (208, 'rapport_ea',U&'Accerder au menu Entrée d\0027Article dans Rapports', ''),

 (210, 'rapport_eb',U&'Accerder au menu Expression de Besoin dans Rapports', ''),

 (212, 'rapport_ci',U&'Accerder au menu Consommation Interne dans Rapports', ''),

 (214, 'rapport_stck',U&'Accerder au menu Stock dans Rapports', ''),

 (216, 'param',U&'Accerder au menu Paramétrage', ''),
 (217, 'param_user',U&'Accerder au menu Utilisateurs', ''),
 (218, 'param_user_new',U&'Créer Utilisateurs', ''),
 (219, 'param_user_edit',U&'Modifier Utilisateurs', ''),
 (220, 'param_user_delete',U&'Supprimer Utilisateurs', ''),

 (222, 'param_grp_user',U&'Accerder au menu Groupe d\0027Utilisateur', ''),
 (223, 'param_grp_user_new',U&'Créer Groupe d\0027Utilisateur', ''),
 (224, 'param_grp_user_edit',U&'Modifier Groupe d\0027Utilisateur', ''),
 (225, 'param_grp_user_delete',U&'Supprimer Groupe d\0027Utilisateur', ''),

 (227, 'param_civi',U&'Accerder au menu Civilité', ''),
 (228, 'param_civi_new',U&'Créer Civilité', ''),
 (229, 'param_civi_edit',U&'Modifier Civilité', ''),
 (230, 'param_civi_delete',U&'Supprimer Civilité', ''),

 (232, 'param_nation',U&'Accerder au menu Nationalité', ''),
 (233, 'param_nation_new',U&'Créer Nationalité', ''),
 (234, 'param_nation_edit',U&'Modifier Nationalité', ''),
 (235, 'param_nation_delete',U&'Supprimer Nationalité', ''),

 (237, 'param_profss',U&'Accerder au menu Profession', ''),
 (238, 'param_profss_new',U&'Créer Profession', ''),
 (239, 'param_profss_edit',U&'Modifier Profession', ''),
 (240, 'param_profss_delete',U&'Supprimer Profession', ''),

 (242, 'param_fonct',U&'Accerder au menu Fonction', ''),
 (243, 'param_fonct_new',U&'Créer Fonction', ''),
 (244, 'param_fonct_edit',U&'Modifier Fonction', ''),
 (245, 'param_fonct_delete',U&'Supprimer Fonction', '')

;